######################################################################
# spring4shell-capstone - vulnerable lab Dockerfile
# --------------------------------------------------------------------
# Builds a Tomcat-9 + Spring-5.3.15 container that is vulnerable to
# CVE-2022-22965 (Spring4Shell).  Used only on *local* networks per
# course policy.
#
#  Maintainer : <Your-Name>  <you@example.com>
#  Created    : 2025-04-25
#  Last mod   : 2025-04-25
#
#  Usage      : docker-compose up -d vuln-lab
#  DANGER     : Never expose this container to the public Internet.
######################################################################